### ISSUE TITLE
go install failed

### ISSUE THREAD

**Issue by jerryan999** [streamingfast/substreams-sink-sql#12]
go: github.com/streamingfast/substreams-sink-postgres@latest: module github.com/streamingfast/substreams-sink-postgres@latest found (v0.0.0-20230130161456-0781169fec63), but does not contain package github.com/streamingfast/substreams-sink-postgres

**Comment by maoueh** [comment]
Can you print the exact command you are doing?

**Comment by maoueh** [comment]
I have fixed the README to list the correct command: `go install github.com/streamingfast/substreams-sink-postgres/cmd/substreams-sink-postgres@latest`

**Comment by jerryan999** [comment]
Thank you for your quick answer! This is a very amazing program!
