### ISSUE TITLE
Reserved sql can not be used as column name

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams-sink-sql#17]
I'm currently mapping 1 to 1 contract events to a table. The `Transfer` event of `ERC20` contracts uses the following arguments:
```
event Transfer(address indexed from, address indexed to, uint256 value)
```

When inserting to the database, I get the following error:
```
ERRO (sink-postgres) handle BlockScopedData message: failed to flush: executing query "INSERT INTO public.erc20_transfer (
block_time,block_number,contract_address,from,to,value,index,tx_hash) VALUES ('2023-04-07T23:58:11Z',17000000,'oLhpkcYhizbB0Z1KLp6wzjYG60g=',
'/LoGk/wW3LKk6Pp+09ox9Slpk+Q=','xFFDxTDp3Aw4lcRYwWAUSjEplVs=','18000000',0,'DACTEGy5GZWAN6aKo854Wkyaj/Qw9OSf0MMqY0juHEY=')": pq: syntax error at or near 
"from"
```

Escaping the columns [here](https://github.com/streamingfast/substreams-sink-postgres/blob/develop/db/operations.go) probably will fix the issue.

**Comment by maoueh** [comment]
There was a pending PR #16 for this already, it was mostly ready. I just merged it, finalize the small nitpick I had and released a new version.

Let me know how it goes.
