### ISSUE TITLE
Numeric types on columns

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams-sink-sql#18]
I want to store token balances using numeric so I can query and filter the data without conversations on the fly for my application perform better.

Currently, `substreams-sink-postgres` converts the column types to go types before running the queries and go doesn't have a types for numeric/bigint. That's why I got the following error:
```
ERRO (sink-postgres) handle BlockScopedData message: failed to flush: failed to get query: preparing column-values: getting sql value from table transfer for column "value" raw v
alue "18000000": unsupported type interface {}
```

[This](https://github.com/streamingfast/substreams-sink-postgres/blob/develop/db/operations.go#L161) is where the error occurs. I can't use uint64 because the data uses uint256. I also can't use text/strings and convert on the fly because it would be a huge performance hit for my application restrictions.

**Comment by maoueh** [comment]
What is the column type of your schema?

**Comment by gusinacio** [comment]
```
create table if not exists Transfer 
(
    id text,
    "from" varchar(42),
    "to" varchar(42),
    "value" numeric,
    primary key (id)
);

```

**Comment by maoueh** [comment]
Thanks, tomorrow I'll take a look.

**Comment by maoueh** [comment]
@flametuner Your suggestion to pass value as-is for unknown column's type has been implemented, I tested it, it fixes the `numeric` problem (of course as long as the received data is correct).

Closing.
