### ISSUE TITLE
Timestamps don't handle already formatted RFC 3339 dates

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams-sink-sql#19]
I'm currently using [substreams-database-change](https://github.com/streamingfast/substreams-database-change) to send `prost_types::Timestamp` as timestamps value.

[The implementation](https://github.com/streamingfast/substreams-database-change/blob/develop/src/change.rs#L46) of `ToField` trait uses the `to_string()` method which already sends the string formatted as RFC 3339 while the [sink implementation](https://github.com/streamingfast/substreams-sink-postgres/blob/develop/db/operations.go#L177) waits for a number inside a string for Unix conversion.

The substreams module works perfectly fine with the following code, but it shouldn't be needed:

```
let unix_timestamp = SystemTime::try_from(value.block_time)
        .unwrap()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();
table_change
        .change("block_time", (None, unix_timestamp));

```

**Comment by maoueh** [comment]
Fixed thanks
