### ISSUE TITLE
`schema` option is not used with cursors table

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams-sink-sql#21]
When trying to use another schema other than `public`, it creates the cursors table in `public` schema.

It also doesn't use the chosen schema for insert and updating, falling back to the `public` again.

**Comment by maoueh** [comment]
Can you add a description, I'm not sure I fully get the issue with just the title.

**Comment by maoueh** [comment]
Ok essentially we are missing using the format `<schema>.<table>` to identify tables I see good.

**Comment by maoueh** [comment]
So we have no place where to define the schema, that would go in the DSN definition, so I would add the `schema` there like:

```bash
substreams-sink-postgres run "psql://dev-node:insecure-change-me-in-prod@localhost:5432/dev-node?sslmode=disable&schema=dataset1" ...
```

And I would use this if defined otherwise `public`, sound good?

**Comment by maoueh** [comment]
In fact I just realized that we actually advertised that but it's not used properly, going to fix that.
