### ISSUE TITLE
Cursors table suggestion doesn't have the right columns

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams-sink-sql#25]
When starting the application without a cursors table created, the CLI send the following message:

```
Error validating the cursors table: %s
You can use the following sql schema to create a cursors table
create table cursors
				(
					id         bigserial not null constraint cursor_pk primary key,
					cursors    text,
					block_num  bigint,
					block_id   text
				);
```

The problem is that if you create the table using the suggested schema, it has errors about the id being an INT instead of TEXT.

I suggest updating the message to:
```
create table if not exists cursors
		(
			id         text not null constraint cursor_pk primary key,
			cursor     text,
			block_num  bigint,
			block_id   text
		);
```

**Comment by maoueh** [comment]
Indeed, the suggestion was not using the same SQL used by the `substreams-sink-postgres setup` command. The two are linked now and `shcema` is correctly referenced.

Release incoming.
