### ISSUE TITLE
Make repo driver agnostics

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams-sink-sql#37]
The repo is actually driver agnostic, thanks to Semiotics team for providing it. The task here is about removing "postgres" from the sink and everywhere. Here the smaller tasks to be performed here:

> [!NOTE]
> Branch `feature/deployable-unit` should be used as a starting point, unless it has been merged already in which case `develop` should be used.

- Rename all Golang packages to be `github.com/streamingfast/substreams-sink-postgres` to become `github.com/streamingfast/substreams-sink-sql`
- Re-write README.md so that repository is clearly defined as an SQL agnostic sinker (I already started a bit I think)
- Rename Github repository  to `substreams-sink-sql`
- Update documentation for all mentions of `substreams-sink-postgres` (we should probably check a few of our `substreams-...` repositories)
- Update the changelog to correctly show everything that needs to be changed with the rename and talk about the fact that is now driver agnostic (I already started a bit I think in `CHANGELOG`)
- Ensure `substreams-sink-sql` Substreams manifest is packaged now with every release (`sfreleaser` is able to package + attach)
- Perform the release

**Comment by sduchesneau** [comment]
All done, in a branch, gotta sync the tutorials and substreams documentation...

**Comment by maoueh** [comment]
We are just missing the release now, closing as no need to track it.
